webtalk_init -webtalk_dir C:/Users/Rongye/OneDrive/FPGA/VerilogHDL/Project/vending_machine/vending_machine.sim/sim_1/behav/xsim/xsim.dir/VENDING_MACHINE_tb_behav/webtalk/
webtalk_register_client -client project
webtalk_add_data -client project -key date_generated -value "Wed Apr 21 10:28:56 2021" -context "software_version_and_target_device"
webtalk_add_data -client project -key product_version -value "XSIM v2019.2 (64-bit)" -context "software_version_and_target_device"
webtalk_add_data -client project -key build_version -value "2708876" -context "software_version_and_target_device"
webtalk_add_data -client project -key os_platform -value "WIN64" -context "software_version_and_target_device"
webtalk_add_data -client project -key registration_id -value "" -context "software_version_and_target_device"
webtalk_add_data -client project -key tool_flow -value "xsim_vivado" -context "software_version_and_target_device"
webtalk_add_data -client project -key beta -value "FALSE" -context "software_version_and_target_device"
webtalk_add_data -client project -key route_design -value "FALSE" -context "software_version_and_target_device"
webtalk_add_data -client project -key target_family -value "not_applicable" -context "software_version_and_target_device"
webtalk_add_data -client project -key target_device -value "not_applicable" -context "software_version_and_target_device"
webtalk_add_data -client project -key target_package -value "not_applicable" -context "software_version_and_target_device"
webtalk_add_data -client project -key target_speed -value "not_applicable" -context "software_version_and_target_device"
webtalk_add_data -client project -key random_id -value "881d39a1-787f-42a9-bab1-8e3d08a6ccf6" -context "software_version_and_target_device"
webtalk_add_data -client project -key project_id -value "0a26ffe1f17349a4802b79f4e0571210" -context "software_version_and_target_device"
webtalk_add_data -client project -key project_iteration -value "10" -context "software_version_and_target_device"
webtalk_add_data -client project -key os_name -value "Windows Server 2016 or Windows 10" -context "user_environment"
webtalk_add_data -client project -key os_release -value "major release  (build 9200)" -context "user_environment"
webtalk_add_data -client project -key cpu_name -value "AMD Ryzen 7 PRO 4750U with Radeon Graphics" -context "user_environment"
webtalk_add_data -client project -key cpu_speed -value "1697 MHz" -context "user_environment"
webtalk_add_data -client project -key total_processors -value "1" -context "user_environment"
webtalk_add_data -client project -key system_ram -value "16.000 GB" -context "user_environment"
webtalk_register_client -client xsim
webtalk_add_data -client xsim -key Command -value "xsim" -context "xsim\\command_line_options"
webtalk_add_data -client xsim -key trace_waveform -value "true" -context "xsim\\usage"
webtalk_add_data -client xsim -key runtime -value "801 ns" -context "xsim\\usage"
webtalk_add_data -client xsim -key iteration -value "0" -context "xsim\\usage"
webtalk_add_data -client xsim -key Simulation_Time -value "0.06_sec" -context "xsim\\usage"
webtalk_add_data -client xsim -key Simulation_Memory -value "6576_KB" -context "xsim\\usage"
webtalk_transmit -clientid 2493995259 -regid "" -xml C:/Users/Rongye/OneDrive/FPGA/VerilogHDL/Project/vending_machine/vending_machine.sim/sim_1/behav/xsim/xsim.dir/VENDING_MACHINE_tb_behav/webtalk/usage_statistics_ext_xsim.xml -html C:/Users/Rongye/OneDrive/FPGA/VerilogHDL/Project/vending_machine/vending_machine.sim/sim_1/behav/xsim/xsim.dir/VENDING_MACHINE_tb_behav/webtalk/usage_statistics_ext_xsim.html -wdm C:/Users/Rongye/OneDrive/FPGA/VerilogHDL/Project/vending_machine/vending_machine.sim/sim_1/behav/xsim/xsim.dir/VENDING_MACHINE_tb_behav/webtalk/usage_statistics_ext_xsim.wdm -intro "<H3>XSIM Usage Report</H3><BR>"
webtalk_terminate
